glacambre/firenvim

package.json
not a great name, but it does not clash with the defined `install` command of yarn.
=> change the name so `yarn install` can install the deps

autoload/firenvim.vim
When firefox was started from a shell running in neovim, firenvim would
connect to this neovim instead of the new instance. Unsetting
NVIM_LISTEN_ADDRESS fixes that.
=> autoload/firenvim.vim: unset NVIM_LISTEN_ADDRESS

README.md
Man (but not all) plugin managers have hook systems for running post-install functions. These not only reduce the number of steps the user has to take the first time but make setting up on other systems easier since they don't have to come back here to find the install command every time, their plugin manager will take care of it any time they install to a new system.
This PR adds instructions for using the ones I know about, and also cleans up the README in other ways.
=> Document plugin install methods that have hooks

.github/workflows/vint.yml, .vintrc.yaml, README.md, autoload/firenvim.vim
This PR does three things:
1. Configures [`vint`](https://github.com/Kuniwak/vint) so you can run it locally on this project (`vint .` from the root)
2. Fixes all the warnings about bad vimscript practices that it turns up
3. Adds a CI job using GitHub Actions that will run the linter on pull requests.
For the latter to work you will need to [signup for Actions on your account](https://github.com/features/actions/signup/?account=glacambre). Additionally after signing up and enabling it for this repository please note that the CI job will not start running until after this PR is merged because a workflow configuration has to exist in `master` before it considers running it on PRs. You can see the CI job in action [on my fork](https://github.com/alerque/firenvim/actions) where I tested it. …
=> Add CI job that validates and lints vimscript

README.md
It looks like the stray '\`.' on the end of this line was my fault and came from editing it out of inline Markdown. Sorry about that.
While I was at it I used a slightly more robust command that will quit nvim if the command succeeds but show more messages and wait for the user if some kinds of errors happen.
=> Fix install command in README, also simplify it

src/background.ts, src/nvimproc/Neovim.ts, src/nvimproc/Stdin.ts, src/nvimproc/Stdout.ts, src/render/Cell.ts, src/render/Cursor.ts, src/render/Grid.ts, src/render/Redraw.ts, src/render/Row.ts, src/utils/CSSUtils.ts, src/utils/utils.ts
Fixing the two legit ones and ignoring the rest (we want to keep the
`import browser from webextension-polyfill` lines because they'll result
in less surprises if we add code that relies on `browser` behaving the
same way in all browsers).
=> Fix lgtm errors

README.md, autoload/firenvim.vim
This enables running code during initialization, when the vimrc is read,
before the OnUIEnter event fires.
Fixes #205
=> Set `g:firenvim_mode` variable when starting nvim.

SECURITY.md, autoload/firenvim.vim, lua/firenvim.lua, src/background.ts
This commit removes a check ensuring that the `Origin` of a websocket
was that of the firenvim webextension which started neovim. This check
is removed because Mozilla decided to remove the `Origin` field of
websocket connections created from a webextension context (see
https://bugzilla.mozilla.org/show_bug.cgi?id=1596889 and
https://bugzilla.mozilla.org/show_bug.cgi?id=1592721).
An alternative would have been to re-create this field with the
webRequest API. However, there are two blockers: this requires a new
permission (I learned from working on Tridactyl that Firefox is pretty
bad at updating extensions that require new permissions) and Chrome is
going to remove the webRequest API anyway.
Note that firenvim should still be secure for the following reasons:
- It binds itself to a random …
=> Make firenvim less secure

src/NeovimFrame.ts, src/render/Grid.ts, src/render/Redraw.ts
On frames larger than the viewport, the keyhandler would make the frame
scroll up, which would prevent users from seeing what they're typing at
the bottom of the frame.
=> Fix keyhandler breaking big frames

src/NeovimFrame.html, src/content.ts, src/utils/CSSUtils.ts
This fixes issues where users would set a non-existing font which would
prevent firenvim from correctly computing the size of the frame.
=> Set default font and default size

src/render/Cell.ts
Before this commit, returning the value was done by fetching
elem.innerText. This somehow forced chrome to recompute styles
(something it apparently did not need to do with the previous scrolling
algorithm) and caused massive performance issues. Simply caching the
value is enough to fix this problem.
Closes #250
=> Cell.ts: cache value

README.md, src/NeovimFrame.ts, src/background.ts
An attempt at fixing #202 and #225.
=> Ignore alt key for non-alphanumeric chars depending on `alt` setting

lua/firenvim.lua, lua/utils.lua, lua/websocket.lua, tests/_common.ts, tests/chrome.ts, tests/firefox.ts
This was caused by websocket frames being split up in multiple TCP
frames. The solution is to make sure we don't process frames until
they're complete.
Closes #179.
=> Fix firenvim breaking on big buffers

README.md
Discussed:
https://github.com/k-takata/minpac/issues/95
https://github.com/glacambre/firenvim/issues/318#issuecomment-570307402
Basically, minpac doesn't load the plugin when it is installed so `firenvim#install(0)` cannot be run. This will probably never be fixed in `minpac` as it uses vim8's builtin package managing feature and loading the package at install time will require a big change.
=> Fix instructions for minpac

.appveyor.yml, autoload/firenvim.vim
These browsers previously worked if chrome was already installed on the
machine. Now they'll work without it.
Closes #180.
Closes #355.
=> firenvim.vim: implement nativemessenger for brave/opera/vivaldi

README.md
1. Fix link to Vimr (unsupported editor variant)
1. List supported browsers (see also #356) because the project name suggests it might be a Firefox only thing.
=> Document supported platforms

src/content.ts, src/page/functions.ts
Unfocusing the active element works around a bug where the iframe
wouldn't be properly refocused on matrix. It's a bit weird but let's not
look a gift fix in the code.
Closes #343
=> functions.ts: unfocus active element before trying to refocus it

src/render/Redraw.ts
This isn't proper support for msg_history_show but should be enough
until the renderer is rewritten.
=> Redraw.ts: implement missing msg_history_show

tests/_common.ts
Guifont fails often on linux. This might be caused by the element not
being properly unfocused.
=> _common.ts: make guifont test more reliable

src/content.ts
This commit places the firenvim frame under Tridactyl's hints and also
makes sure that the iframe is correctly re-focused when focused with
Tridactyl.
=> Make Firenvim play nicer with Tridactyl

README.md, SECURITY.md, lua/firenvim.lua, lua/websocket.lua, src/NeovimFrame.ts, src/background.ts, src/nvimproc/Neovim.ts, src/nvimproc/Stdout.ts, src/render/Grid.ts, src/render/Redraw.ts, src/utils/configuration.ts
Currently buggy if `:qall!` is used.
Closes #197
=> Implement persistent server

.travis.yml
The binary cache doesn't seem to work for OSX. This is an attempt at
fixing it.
=> .travis.yml: use paths relative to $HOME on osx

src/editors/MonacoEditor.ts
GitLab seems to use a sligtly modified Monaco editor in the GitLab Web IDE. With this minor change firenvim works well within GitLab Web IDE.
=> Correctly detect Monaco editor in GitLab Web IDE

README.md
The sentence was a little convoluted and didn't explicitly mention that the pattern has to match the full URL.
=> Reword config dictionary explanation in README.md

src/editors/CodeMirrorEditor.ts
Modified the regexp used to detect the CodeMirror root element during CodeMirror detection. Now it checks to make sure the class it is looking for *starts* with CodeMirror, as opposed to just containing “CodeMirror” This prevents it from matching `jp-CodeMirrorEditor`, which is a Jupyter wrapper class that doesn’t expose the correct API. Instead it will now correctly match the CodeMirror root in JupyterLab cells.
=> Fix CodeMirrorEditor for JupyterLab support

README.md
Added a significant section to the README that explains the issues with alt on
MacOS in more detail.
=> update documentation on special chars in macos

autoload/firenvim.vim, src/nvimproc/Neovim.ts, src/utils/utils.ts, tests/_common.ts
This PR tries to provide an *optional* argument `callback_name` to the function `firenvim#eval_js`. 
The new signature of this function will be like the following:
```vim
firenvim#eval_js(code: string, callback_name?: string)
```
In this way, we can handle the result of the javascript evaluation in the vim script.
```vim
function EvalJSCallback(result)
echom 'result' a:result
endfunction
function EvalJS()
let js = "location.href"
call firenvim#eval_js(js, 'EvalJSCallback')
endfunction
```
output: `result "https://www.google.com"`
```vim
function EvalJSCallback(result)
echom 'result' a:result
endfunction
function EvalJS()
let js = "new Promise(resolve => fetch('https://jsonplaceholder.typicode.com/todos/1').then(response => response.json()).then(resolve))"
call firenvim#eval_js(js, …
```
=> improve: add callback as an optional argument to handle eval_js result

autoload/firenvim.vim
fixes #773
confirmed linux and mac paths (do not have a machine to test windows)
=> fixes installing fire nvim on brave

autoload/firenvim.vim
This commit uses XDG_CONFIG_HOME and fallsback to ~/.config if the env var is not set.
Follow-up to #778
=> Better support the XDG folder spec on Linux

TROUBLESHOOTING.md
The sourcehut repo has an older version that will not work with the
current browser extension version. 
Fixes #1008
=> use more recent version on github instead of sourcehut

autoload/firenvim.vim
The description says firefox in chrome and chromium manifests which is briefly confusing when troubleshooting. This description matches what's found in package.json.
=> changed firefox to generic browser

autoload/firenvim.vim
Fixes #1005.
Tested on  Version 91.0.4464.5 (Official Build) dev (x86_64). firenvim.json created in `$HOME/Library/ApplicationSupport/Google/Chrome Dev/NativeMessagingHosts`.
```json
{ "name": "firenvim", "description": "Turn Firefox into a Neovim client.", "path": "$HOME/.local/share/firenvim/firenvim", "type": "stdio", "allowed_origins": [ "chrome-extension://egpjdkipkomnmjhjmdamaniclmdlobbo/" ]}
```
=> chrome dev manifest creation on mac

TROUBLESHOOTING.md
Steps I followed to deal with #1007. My configs were in a folder in `~/Documents` and used symlinks in `~/.config/nvim`. They had read permissions but when trying to load them from firenvim with `-u NORC`, firenvim couldn't load any files in `~/Documents`.
=> check if firenvim can access configs not in default location

src/background.ts
Hi dear author, 
I just tried `firenvim`, it works really great in Chrome, it can even edit local files, which makes it a true GUI client for `neovim`. And I also would like to integrate it with `Surfingkeys` as people suggested here https://github.com/brookhong/Surfingkeys/issues/1064.
This PR is to make `firenvim` to listen external message and handle incoming message as commands, which has not limited to special senders. If you'd like the senders limited to a certain list, please let me know.
=> Add listener for external message, so that it can be integrated.

README.md
If I understand how press_keys works, I think there's a typo there.
=> README: Fix typo in #press_keys()

autoload/firenvim.vim
Imagine the following scenario:
- You are running a neovim appimage
- In that neovim instance, you have a terminal buffer
- In that terminal buffer, you run firefox/chrome/thunderbird
- You close down your neovim instance
The neovim appimage will have created four environment variables: $VIM,
$VIMRUNTIME, $APPDIR and $APPIMAGE. The browser will have inherited
these environment variables. When firenvim attempts to start a new
neovim instance, the new neovim instance inherits these variables.
The new neovim instance will attempt to use the runtime in $VIM and
$VIMRUNTIME, but won't find it, because the directories $VIM and
$VIMRUNTIME are pointing to were deleted when the parent appimage
shut down. This can potentially results in errors that prevent firenvim
from starting altogether.
We fix …
=> Unset $VIM and $VIMRUNTIME if not pointing to directories

src/Neovim.ts, src/frame.ts, src/input.ts, src/renderer.ts
This code extracts the browser-specific input code from input.ts (which
is supposed to be generic across thunderbird and browsers) and moves it
to frame.ts (which is browser-only).
In order to do so, input.ts can't directly reference the frame
keyhandler's anymore, instead an NvimInputEmitter class is created in
order to have a an object that deals with platform-specific intricacies
and offer a generic input event emitter that can be directly fed to
Neovim. Implementation of the thunderbird event emitter will happen in a
later commit.
This change also required breaking the direct reference to the renderer
the input-handling code had. This dependency was required in order to be
able to process key events differently depending on the current mode.
The choice made here was to have the …
=> Refactor event handling

src/compose.ts, src/input.ts, src/page.ts
- refactor: replace manual browser.runtime listener with EventEmitter
=> thunderbird resize

src/compose.ts
Logging had a huge perf impact when combined with autosync.
=> thunderbird: stop logging calls to PageEventEmitter

src/background.ts, src/compose.ts, src/page.ts
This works around a thunderbird bug where cancelling beforeinput events
on the compose window's document will prevent the onBeforeSend listener
from setting the compose window's content.
Closes #1169
=> thunderbird: fix plaintext editing

src/background.ts, src/utils/configuration.ts
This is useful to the qutebrowser port but deserves a live of its own.
=> Extract default config generation to utils/configuration.ts

README.md
Nvim needs to improve the UX here by always setting some fields.
Meanwhile, this example can be less verbose.
=> README.md: improve UIEnter example

autoload/firenvim.vim
=> better wsl support

.github/workflows/test.yml
Need this to allow building neovim when download fails. Code reviewed.
=> Upgrade action-setup-vim to latest commit

src/page.ts, src/utils/utils.ts
=> Use window.eval for executeInPage on Firefox when possible

autoload/firenvim.vim, src/background.ts, tests/_common.ts, tests/chrome.ts, tests/firefox.ts
Thanks to https://github.com/neovim/neovim/pull/15910 we can now work
around broken configs and start firenvim despite the user messing things
up. Cherry on top, we can warn them through the browser UI.
Closes #1196, #1209
=> fix firenvim being unable to start due to broken configs

autoload/firenvim.vim
I only tested this on Linux, and it worked. I based files locations for
other platforms on
<https://librewolf.net/docs/settings/#where-do-i-find-my-librewolfoverridescfg>.
I assume the registry key location requires changing. Unfortunately,
I have no convenient way of testing this beyond Linux.
=> Add support for LibreWolf

src/background.ts
This can happen when a browser tab (e.g. about:debugging) is focused.
=> background.ts: don't fail on non-existing tabs

autoload/firenvim.vim
`$HOME/.nix-profile` isn't enough; it will only ever exist (i.e. point
to a valid profile in `/nix/var/nix/profiles`) if the user installs
software via `nix-env`. Many nix users, and indeed most nixOS users,
configure their systems through `user.packages` and/or
`environment.systemPackages`. While the latter creates symlinks
in `/run/current-system/sw/bin`, the former does not.
`/etc/profiles/per-user/$USER` will contain symlinks for packages
installed via `user.packages` *and* those installed via home-manager's
`home.packages`.
=> feat(nix): add another path to the set of contant_paths

src/Stdout.ts
The previous handling of slicing partially-buffered data based on the decoded and later encoded message turned out to be faulty. I suspect the encoded message could have a different byte length than the received message. The fact that [the Neovim change](https://github.com/neovim/neovim/commit/5d6987210578f5f1c3151988b99a9411f9603374#diff-a1fbec4cf4e555c5adb8e700b2f7f4f7368f0317c9e2b0b5a3112f273df794bfR83) mentioned in #1382 uses fixed-size arrays may support this claim.
The `msgpack.Decoder` class already does that logic internally. The difference is that it knows exactly how many bytes were read. It can [slice the internal buffer in a more precise way](https://github.com/kawanet/msgpack-lite/blob/5b71d82cad4b96289a466a6403d2faaa3e254167/lib/flex-buffer.js#L91).
I didn't run the jest …
=> Use `msgpack.Decoder` to decode WebSocket messages

src/renderer.ts
Fusing messages and cmdline isn't ideal, but as neovim doesn't offer a
way to get separate cmdline and messages, it's probably better not to
offer a second configuration option that only works conditional on the
"cmdline" setting.
=> Also disable messages when cmdline is set to "none" (#1442)

README.md
Now you don't have to enable firenvim manually to run the install script when you're updating your plugins from the terminal. Thanks to @axieax for the build function.
=> Updated the install instructions for lazy.nvim

src/manifest.json
At least on Chromium 113.0.5672.126 (the current version in Fedora 37), command descriptions with strings that look like HTML tags (e.g. \<C-w\>) prevent that option and all the options that follow from being shown in chrome://extensions/shortcuts.
Unknown tags, \<script\> and probably others trigger this error. Some tags like \<b\> don't trigger it but they are parsed as plaintext, so this looks like a Chromium bug.
Anyway, this patch replaces \<C-w\> and similar with Ctrl-w allowing commands to be configured in chrome://extension/shorcuts. I tried escaping the original text but didn't find a way.
=> Fix chrome://extensions/shortcuts missing options

README.md
The previous installation instructions no longer work as @folke has updated the cond keyword to behave the same as the enabled keyword, which means that firenvim wouldn't install after an update because lazy.nvim will not load disabled plugins.
=> Updated the installation instructions for lazy.nvim

README.md, src/utils/configuration.ts
What this PR is trying to fix: given https://github.com/glacambre/firenvim/blob/master/tsconfig.json as an example, clicking in the code will trigger firenvim to start an nvim instance. This should not happen, the textarea can't be edited
Tested manually first with the default values
```js
document.querySelectorAll('textarea:not([readonly]), div[role="textbox"]')
```
and with
```js
document.querySelectorAll('textarea:not([readonly], [aria-readonly]), div[role="textbox"]')
```
Tested locally by building the extension with `DOCKER_BUILDKIT=1 docker build . -t firenvim --output target`
Closes #1537
=> Exclude 'aria-readonly' in localSettings selector

autoload/firenvim.vim
Firenvim on Windows relys on powershell scripts to run registry keys installation and uninstallation. Here are the codes:
https://github.com/glacambre/firenvim/blob/8c6c00aae7e5762cbcb4cd0df5848e959c4a9572/autoload/firenvim.vim#L890
https://github.com/glacambre/firenvim/blob/8c6c00aae7e5762cbcb4cd0df5848e959c4a9572/autoload/firenvim.vim#L958
During debugging, I add `echo o` right after calling the `system` function, which then shows error
```text
Cannot load PSReadline module.  Console is running without PSReadline.
```
But weirdly, `v:shell_error` is still `0`. `PSReadline` is a module usually installed for interactive prompt usage. `Powershell.exe` provides option `-NonInterative` for running automated scripts in non-interactive shell. Adding the `-NonInteractive` option fixes #1547 as …
=> fix: run scripts in noninteractive shell (#1547)

autoload/firenvim.vim
Variable `s:is_wsl` indicates whether firenvim is running on the WSL side or on the Windows host system. Currently, `s:is_wsl` checks three environment variables `$WSLENV`, `WSL_DISTRO_NAME`, and `WSL_INTEROP`. The following table lists the values of these env vars on the host system and on the WSL2 system:
| ENV_VAR            | Windows Host                | WSL2                        |
|--------------------|-----------------------------|-----------------------------|
| `$WSLENV`          | `WT_SESSION:WT_PROFILE_ID:` | `WT_SESSION:WT_PROFILE_ID:` |
| `$WSL_DISTRO_NAME` | empty                       | `Ubuntu-22.04`              |
| `$WSL_INTEROP`     | empty                       | `/run/WSL/1133_interop`     |
The incorrect env var `$WSLENV` is used in …
=> fix: remove incorrect WSL env variable (#1578)

TROUBLESHOOTING.md
`%APPDATA%` points to `%UserProfile%/AppData/Roaming`, while `%LOCALAPPDATA%` points to `%UserProfile%/AppData/Local`. `%LOCALAPPDATA%` should be used when refering to firenvim script path
[Reference](https://superuser.com/a/632905)
=> chore(doc): use correct env var in TROUBLESHOOTING

autoload/firenvim.vim
The uninstallation logic is similar to `firenvim#install`:
> At first, is_wsl is set to false, even on WSL. This lets us uninstall
firenvim on the wsl side.
> Then, we set is_wsl to true if we're on wsl and launch
firenvim#uninstall again, uninstalling things on the host side.
=> fix: add uninstall on host side from WSL (#1576)

autoload/firenvim.vim
`vim.fn.has()` or `has()` can help check current runtime condition.
As `:h has()` indicates:
> Returns 1 if {feature} is supported, 0 otherwise.
> ...
> 2. Runtime condition or other pseudo-feature. For example the
>     "win32" feature checks if the current system is Windows:
>         :if has("win32")
>         				*feature-list*
>     List of supported pseudo-feature names:
>         ...             ......
>         wsl		WSL (Windows Subsystem for Linux) system.
Inspired from:
https://github.com/neovim/neovim/blob/dc466f9a63ede5e2bbddc33688c0c972abfe9a52/runtime/autoload/provider/clipboard.vim#L132
=> refactor: add has('wsl') to help set s:is_wsl

TROUBLESHOOTING.md
The http://txti.es website shut down in July 2023:
> Due to bad actors, txti will be shutting permanently on
> July 1, 2023.
This commit removes the references to txti.es from
TROUBLESHOOTING.md.
=> TROUBLESHOOTING.md: Remove reference to txti.es

src/Neovim.ts, src/frame.ts
- src/frame.ts: replace nvim_call_atomic with nvim_exec_lua
- src/Neovim.ts: stop filtering out deprecated functions.
=> Stop relying on call_atomic

autoload/firenvim.vim, src/frame.ts
- firenvim.vim: filter out g:firenvim_config objects that can't be json
- Add firenvim#write() function enabling users to write arbitrary data
=> enable arbitrary writes

package.json, src/FirenvimElement.ts
- package.json: add lint step to lint firefox extension
- FirenvimElement.ts: use s/browser.extension/browser.runtime/
=> Light extension linting

autoload/firenvim.vim
- firenvim.vim: also handle homebrew installed in /opt/homebrew
- firenvim.vim: attempt to use nvim in $PATH if found
Closes #1614
=> Attempt to work around homebrew on OSX

autoload/firenvim.vim
When creating the `.sh` script for Linux, "NVIM_APPNAME" is set as expected. This does not happen on Windows, however. I've added a new function, `s:capture_windows_env_var`, which adds a statement formatted like:
```bat
if NOT DEFINED some_variable (
set "some_variable=some_value"
)
```
The only environment variable added to the batch script is NVIM_APPDATA
=> Capture NVIM_APPNAME on Windows during batch script installation

autoload/firenvim.vim
This PR is a continuation of #1199 and #1577. #1199 adds support for running `powershell.exe` when it's not in the path (this occurs when WSL user sets `appendWindowsPath=false` in `/etc/wsl.conf`). #1577 adds `-NonInteractive` option to `powershell.exe` commands.
=> fix: use noninteractive powershell

autoload/firenvim.vim
The behaviors of `firenvim#install` and `firenvim#uninstall` on WSL are controlled by the script variable `s:is_wsl`: we initialize it to false to (un)install firenvim on wsl side, and then set it to 1 to (un)install on windows host side.
Currently, only `firenvim#install` and `firenvim#uninstall` changes the value of `s:is_wsl`. The two function do not reset `s:is_wsl`, and thus `s:is_wsl` is always 1 after calling them.
As a result, doing the followings sequentially in neovim have unexpected results:
```lua
-- 1. `s:is_wsl` is set to 1
vim.fn["firenvim#install"](0)
-- 2. uninstall firenvim only on windows host because `s:is_wsl` is 1
vim.fn["firenvim#uninstall"]()
```
```lua
-- 1. `s:is_wsl` is set to 1
vim.fn["firenvim#uninstall"]()
-- 2. reinstall, installs scripts on host only, no …
```
=> fix: reset s:is_wsl after calling (un)install

.github/workflows/test.yml, package-lock.json, package.json, src/Neovim.ts, src/frame.ts, src/renderer.ts
Issue #1637 reports that resizing the underlying textarea of a Firenvim iframe can result in flashes of color. This can be particularly visible when using Firenvim with a dark colorscheme on Github in dark mode.
The reason for these flashes of color is that when resizing, the iframe gets resized first and the Neovim canvas gets resized second, between these two moments, the iframe's background color can become visible if the CSS colorscheme of the iframe and of the website do not match.
We fix this by ensuring that the iframe's background color is set to the background color of the Neovim colorscheme. This breaks the ability of the iframe to turn transparent when unfocused (the iframe gets dimmed instead), but given that multiple users complained about this feature, it may not be such a …
=> Set iframe background color on neovim's default_colors_set (#1637)

autoload/firenvim.vim
Oddly enough, edge on OSX has already been reported as working in #560, but for some reason #1651 reports a different installation path. Check for both.
Closes #1651.
=> firenvim.vim: check for more edge install paths on OSX

autoload/firenvim.vim
Fix #1651 for real :). Verified locally by command `nvim +'call firenvim#install(0)' +q`. Saw the firenvim.json file installed under `~/Library/Application Support/Microsoft Edge/NativeMessagingHosts`.
=> Fix the NativeMessagingHosts path for Microsoft Edge

autoload/firenvim.vim, plugin/firenvim.vim
This prevents issues with Vim.
=> Move FirenvimUIEnterAugroup creation to firenvim#run for #1660

.github/workflows/vint.yml
vint.yml is failing due to the required python version being
unavailable. Can we stop asking for a specific version?
=> vint.yml: try to get rid of setup-python action

.github/workflows/test.yml
Hopefully will make the failures to download neovim stable on linux
disappear.
=> test.yml: upgrade action-setup-vim to latest version

autoload/firenvim.vim
In #1683, the user reports that get_windows_env_path returns truncated
values for %AppData%, and that replacing the `-3` to `-2` in the value
returned by get_windows_env_path fixes this issue.
On my machine, it seems that `-3` is still the correct value. This is
weird, because system()'s `:help` says that CRs should be stripped from
`system()`'s output, meaning that regardless of whether the system emits
an NL or a CRNL, the string system returns should be consistent.
We just shrug our shoulders at this mistery and start using trim()
instead of hard-coding the amount of characters to remove from
system()'s output in order to fix this.
Closes #1683
=> firenvim.vim:get_windows_env_path: deal with inconsistent system()
