glacambre/firenvim

src/NeovimFrame.ts
src/content.ts
src/nvimproc/Neovim.ts
src/page/functions.ts

Update selectionStart on bufwrite

---

src/background.ts
src/content.ts
src/manifest.json
src/page/functions.ts
tslint.json
webpack.config.js

Enable shortcut to trigger firenvim

---

autoload/firenvim.vim

Problem: Default execution policy disallows executing .ps1 files:
:!powershell C:/Users/foo/AppData/Local/firenvim/chrome.ps1
C:/Users/foo/AppData/Local/firenvim/chrome.ps1 : File
C:\Users\foo\AppData\Local\firenvim\chrome.ps1 cannot be
loaded because running scripts is disabled on this system. For more
information, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ C:/Users/foo/AppData/Local/firenvim/chrome.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : SecurityError: (:) [], PSSecurityException
+ FullyQualifiedErrorId : UnauthorizedAccess
Solution: feed the commands to powershell as input.
Also:
- Do not append "-ErrorAction SilentlyContinue" to the powershell commands.
It doesn't seem necessary, even if …

firenvim#install: powershell: feed commands instead of .ps1 file

---

package-lock.json

Update packages to prevent handlebar security vulnerability.

---

src/content.ts

content.ts: nvimify new elements if they're the currently active element

---

lua/firenvim.lua
src/background.ts
tslint.json

https://github.com/glacambre/firenvim/issues/49

Force exit if :qall doesn't work

---

src/NeovimFrame.ts
src/background.ts
tests/_common.ts
tests/_vimrc.ts
tests/chrome.ts
tests/firefox.ts

Make sure dead frames disappear

---

src/NeovimFrame.ts

NeovimFrame.ts: ignore events if they're composing

---

src/content.ts
src/page/functions.ts
tsconfig.json

Fix frames reappearing when typing text in elements modifies DOM

---

src/NeovimFrame.ts
tslint.json

NeovimFrame.ts: take altGr into account

---

src/NeovimFrame.ts
src/render/Redraw.ts
tests/_common.ts
tests/chrome.ts
tests/firefox.ts

Render.ts: make sure not to overwrite guifont on empty guifont{set,wide}

---

src/content.ts
src/page/functions.ts
src/utils/utils.ts
tests/_common.ts
tests/chrome.ts
tests/firefox.ts

Add monaco support

---

README.md

- Use only a single top heading in the doc
- Add empty line after headings
- Consistently set vim as the language for relevant code blocks
- Surround code blocks with empty lines
- Use more idiomatic vimscript and use consistent indentation

README style improvements

---

README.md
autoload/firenvim.vim
src/nvimproc/Neovim.ts
src/page/functions.ts

Add firenvim#focus_page()

---

README.md

Thanks so much for this awesome plugin @glacambre!
I hope to be useful

README.md: Fix missing parameter in UIEnter event

---

src/background.ts
src/content.ts
src/page/functions.ts
src/utils/configuration.ts
tests/_common.ts
tests/chrome.ts
tests/firefox.ts

Closes https://github.com/glacambre/firenvim/issues/265

Implement takeover: once

---

src/content.ts
src/utils/configuration.ts
tests/_common.ts
tests/chrome.ts
tests/firefox.ts
tslint.json

Implement takeover: nonempty

---

src/NeovimFrame.html
src/NeovimFrame.ts
src/background.ts
src/nvimproc/Neovim.ts
src/render/Redraw.ts
src/utils/configuration.ts

Implement external commandline

---

autoload/firenvim.vim
tests/_common.ts
tests/chrome.ts
tests/firefox.ts

Closes https://github.com/glacambre/firenvim/issues/315

firenvim.vim: fix g:started_by_firenvim not being set on windows

---

src/content.ts

content.ts: fix frame not following textarea on appends to page

---

src/render/Redraw.ts

Redraw.ts: fix invisible cursor on set guicursor=

---

lua/utils.lua
lua/websocket.lua

lua: fix missing `bit` dependency on non-luajit neovim

---

src/firenvim.d.ts
src/render/Redraw.ts
src/utils/CSSUtils.ts

Implement support for other text attrs (underline, bold…)

---

src/content.ts

content.ts: check takeover status when nvimifying on element creation

---

src/background.ts
src/manifest.json
src/page/functions.ts

Note that these don't work on firefox for linux because of a Firefox bug
but this will probably be fixed someday.
Closes #236

Implement focus_* browser shortcuts

---

src/NeovimFrame.ts
tests/_common.ts

NeovimFrame.ts: Fix <S-Left> not working

---

src/content.ts

content.ts: fix forceNvimify not working when takeover=non/empty

---

.appveyor.yml
package-lock.json
package.json
src/manifest.json
webpack.config.js

That's one less thing to do when publishing new releases!
Closes #106

Have webpack automatically generate png icons from svg

---

src/NeovimFrame.ts
tests/_common.ts
tests/chrome.ts
tests/firefox.ts

This commit:
- Coalesces window population + cursor movement in a single RPC
operation removing latency
- Refactors and reduces testing delays
- Removes dead tests

Improve testsuite

---

autoload/firenvim.vim

firenvim.vim: use XDG_RUNTIME_DIR instead XDG_DATA_DIR

---

tests/_common.ts
tests/firefox.ts

This commit introduces a function that enables making sure that Firenvim
is ready to receive input before sending some.

Make testsuite more reliable

---

tests/_common.ts

KeyDelay was necessary when the testsuite was flakier. We can remove it
now that it's more robust. We increase FIRENVIM_INIT_DELAY a little
because Chrome is still flaky.

tests/_common.ts: remove keyDelay

---

release.sh
src/manifest.json
webpack.config.js

These are random changes that I hope will fix whatever the chrome web
sotre dislikes about new Firenvim releases.

Update extension manifest

---

src/render/Redraw.ts

Redraw.ts: fix colors being erroneously set to default

---

tests/_common.ts
tests/chrome.ts
tests/firefox.ts

_common.ts: implement test to ensure that neovim instances do not linger

---

tests/_common.ts

This makes logs nicer in case of errors.

tests/_common.ts: use expect in more places

---

src/NeovimFrame.ts
src/content.ts
src/editors/AbstractEditor.ts
src/editors/AceEditor.ts
src/editors/CodeMirrorEditor.ts
src/editors/MonacoEditor.ts
src/editors/TextareaEditor.ts
src/page/functions.ts
src/utils/utils.ts
tests/_common.ts
tests/pages/ace.html
tests/pages/monaco.html

Detect filetype and use according extension when possible

---

src/FirenvimElement.ts
src/content.ts
src/page/functions.ts
tests/_common.ts
tests/chrome.ts
tests/firefox.ts

Ensure iframe is smaller than window and doesn't overflow

---

src/FirenvimElement.ts
src/page/functions.ts

Fix frame sticking to viewport

---

README.md
src/FirenvimElement.ts
src/NeovimFrame.ts
src/background.ts
src/manifest.json
src/page/functions.ts
src/utils/configuration.ts

Closes https://github.com/glacambre/firenvim/issues/103

Allow overriding `<C-w>`

---

README.md
autoload/firenvim.vim
autoload/firenvimft.vim
plugin/firenvim.vim

@alerque Does this fit what you had in mind for https://github.com/glacambre/firenvim/issues/268 ? One thing I'm concerned about is that if we add a rule for every website people use this might end up being slow.
I guess if this ever happens we could rewrite this as a partial trie but I'm wondering whether this would be worth the complexity, I'm happy using the `text` filetype most of the time.

Add filetype-detection mechanism

---

src/NeovimFrame.ts
tests/_common.ts
tests/chrome.ts
tests/firefox.ts

Closes https://github.com/glacambre/firenvim/issues/491

Trigger FocusGained/Lost autocmds on focus gain/loss

---

src/nvimproc/Stdout.ts

The transport layer should now be pretty solid.

nvimproc/Stdout.ts: correctly parse messages

---

autoload/firenvim.vim
lua/firenvim.lua
tests/_common.ts

autoload/firenvim.vim: don't close channel, await closure from parent

---

src/render/Redraw.ts

Redraw.ts: use attr_id for cursor color

---

autoload/firenvim.vim
src/nvimproc/Neovim.ts
src/page/functions.ts
tests/_common.ts
tests/chrome.ts
tests/firefox.ts

Implement firenvim#eval_js

---

src/FirenvimElement.ts
src/content.ts

Closes https://github.com/glacambre/firenvim/issues/548

Fix firenvim frame not reappearing on input appearance/disappearance.

---

README.md

One thing I am unsure about is the explanation of the "external command line" - I definitely think this needs an explanation, it is quite useful yet I had no idea what it was when I first read the README. Now I am just starting to explore it, but so far it's looking good.

Improve wordings in README.md

---

autoload/firenvim.vim

firenvim.vim: add chrome canary support

---

src/utils/keys.ts
tests/_common.ts
tests/pages/chat.html

Fix modifiers not being registered for special keys

---

src/FirenvimElement.ts

FirenvimElement: use MutationObserver to track element presence in page

---

autoload/firenvimft.vim

Currently filetype detection does not work on reddit since, at least for me, it always redirects to the url variant with www prefix.

Add www prefix to reddit.com in firenvimft.vim

---

README.md
SECURITY.md
lua/firenvim.lua
src/NeovimFrame.ts
src/background.ts
src/utils/configuration.ts

Remove persistent server

---

src/utils/keys.ts
tests/pages/chat.html

Add keycodes to key events generated by press_keys

---

package.json
release.sh
src/FirenvimElement.ts
src/NeovimFrame.ts
src/background.ts
src/compose.ts
src/manifest.json
src/utils/configuration.ts
src/utils/utils.ts
webpack.config.js

This works but a few issues remain around focus/replies. I have to put this on
hold as I can't build anymore because v8 crashes every time I invoke npm. I'll
need to fix that before being able to resume work on thunderbird support.
Closes #314.

Thunderbird support

---

src/background.ts
src/common.ts
src/compose.ts
src/content.ts
src/utils/utils.ts

- compose.ts: prepare buffer info before attaching elem to page
- utils.ts: improve thunderbird detection
- Refactor code to share more logic between thunderbird and browsers
Closes #777

thunderbird improvements

---

src/background.ts
src/editors/TextareaEditor.ts
src/utils/configuration.ts
tests/_common.ts
tests/chrome.ts
tests/firefox.ts
tests/pages/contenteditable.html

As discussed in issue #812, this adds a localSetting to specify if the content
should be treated as text or html.

Html escaping

---

src/FirenvimElement.ts
src/NeovimFrame.ts
src/nvimproc/Neovim.ts
src/page/functions.ts
tests/_common.ts
tests/chrome.ts
tests/firefox.ts

killEditor: don't focus input if editor isn't focused

---

src/background.ts
src/common.ts
src/page/functions.ts

Fix lastFocusedContentScript not being properly propagated

---

.github/workflows/test.yml
src/FirenvimElement.ts
src/Neovim.ts
tests/_common.ts
tests/chrome.ts
tests/firefox.ts

Closes https://github.com/glacambre/firenvim/issues/904

more coverage3

---

src/editors/AceEditor.ts

Jenkins fix dry

---

Dockerfile

Follow up to #1014, keeping things simple. If a newer neovim is really needed there is a semi-official PPA with nightly builds, but I don't see the need.

Simplify Docker builder

---

src/editors/MonacoEditor.ts

Added file to the regex that checks the data-uri attribute.

Fixing file type on Monaco Editor.

---

src/frame.ts
src/input.ts
src/page.ts

This was overly complicated for no good reason.

Simplify internal frame setup functions

---

src/EventEmitter.ts
src/Neovim.ts
src/Stdout.ts

Another attempt at refactoring things for thunderbird, which might work
better than the events-as-list-of-promises attempt made previously.

Create EventEmitter class

---

src/input.ts

Re-enable swap files

---

.github/workflows/test.yml

CI: update coverage-comparison github action to v1.0.0

update coverage action

---

src/KeyHandler.ts
src/autofill.ts
src/compose.ts
src/frame.ts
src/input.ts
src/utils/configuration.ts

Currently only supports compose windows, not reply windows, because of
https://bugzilla.mozilla.org/show_bug.cgi?id=1675589

Initial thunderbird support (again)

---

webpack.config.js

Closes https://github.com/glacambre/firenvim/issues/984

Thunderbird: upgrade required version to nightly

---

README.md
src/background.ts
src/input.ts
src/utils/configuration.ts
src/utils/utils.ts
tests/_common.ts
tests/chrome.ts
tests/firefox.ts

Closes
https://github.com/glacambre/firenvim/issues/1081
https://github.com/glacambre/firenvim/issues/1101

Make filename configurable

---

README.md
src/background.ts
src/input.ts
src/utils/configuration.ts
tests/_common.ts
tests/chrome.ts
tests/firefox.ts

We previously chose to let users implement this themselves if they
wanted it, but it makes more sense for Thunderbird to do this out of the
box and by default, so here's a new setting.
Closes #1143

New feature: autosync

---

src/compose.ts

thunderbird: make `:q` close compose window

---

src/background.ts
src/compose.ts

When writing HTML emails, the canvas would stay in the document and be
sent along with the email's content.
This didn't happen for plaintext emails.

thunderbird: fix canvas being sent with email

---

README.md
src/Neovim.ts
src/background.ts
src/compose.ts
src/input.ts
src/page.ts
src/utils/configuration.ts
tests/_common.ts
tests/chrome.ts
tests/firefox.ts

- Revert "New feature: autosync"
- Make HTML editing usable

thunderbird html editing

---

src/compose.ts

thunderbird: remove scrollbars on long emails

---

src/compose.ts

This helps with situations where the compose window starts scrolled
down.
Closes #1174

thunderbird: make canvas position fixed

---

src/compose.ts

thunderbird: hide remaining compose UI elements

---

package-lock.json
package.json

Upgrade editor-adapter

---

autoload/firenvim.vim

https://github.com/neovim/neovim/pull/15211

Fix breakage caused by neovim nightly change

---

src/renderer.ts

Fix negative-width/negative-space characters breaking the renderer

---

tests/firefox.ts

- tests/firefox.ts: disable browser shortcuts tests

disable browser shortcuts test

---

src/manifest.json
src/options.html
webpack.config.js

Add instructions about configuring neovim to webextension page

---

README.md
src/manifest.json

Just a test to see what the CI complains about.

manifest.json: remove "tabs" permission

---

autoload/firenvim.vim
src/FirenvimElement.ts
src/Neovim.ts
src/compose.ts
src/page.ts
tests/_common.ts
tests/chrome.ts
tests/firefox.ts
tests/pages/focusnext.html
tests/pages/focusnext2.html

Closes https://github.com/glacambre/firenvim/issues/1270 .

Add firenvim#focus_next and firenvim#focus_prev

---

autoload/firenvim.vim

firenvim.vim: make generated script easier to read

---

src/utils/configuration.ts

Fixes https://github.com/glacambre/firenvim/issues/1318.

configuration.ts: enforce correct types in user config

---

lua/firenvim.lua

Fix breakage caused by removal of $NVIM_LISTEN_ADDRESS

---

.github/workflows/test.yml

Required to get CI working again.

Upgrade install-neovim action to 1.2.11

---

release.sh

release.sh: use git-archive instead of tarring sources manually

---

src/autofill.ts
src/content.ts

Fix issue autofill not working reliably

---

README.md
autoload/firenvim.vim

README.md: update installation requirements

---

autoload/firenvim.vim

Change vivaldi manifest path (#1433)

---

tests/_common.ts

This test started failing, probably due to a chrome change.

tests/_common.ts: fix modifier test failing on linux chrome

---

src/KeyHandler.ts

Fix IME handling

---

autoload/firenvim.vim

This should solve complex path issues.
Closes #1458 #1459 #1460

firenvim#install(): on wsl, make firenvim.bat run firenvim.sh

---

autoload/firenvim.vim

- firenvim script: move additional logged messages to stderr
- firenvim#run(): make sure error messages are sent to stderr

loggging improvements

---

README.md

I also included how to lazy load firenvim using lazy.nvim as well.

Added installation instructions for lazy.nvim

---

README.md

README.md: convert examples to Lua

---

src/frame.ts
src/renderer.ts

Do not react to mouse when `:set mouse=`

---

autoload/firenvim.vim

- firenvim.vim: fix indentation
- firenvim.vim: define empty g:firenvim_config before running nvim

foolproof some more

---

src/content.ts

Just extruding some functions which look like they do not capture any
variables. Let's see what happens.

Hopefully harmless refactor

---

README.md
autoload/firenvim.vim

Add support for Arc browser which runs only on MacOS.
This patch works for me.
for more information about Arc browser:

add: Arc browser support.

---

README.md

Updates language as promised in  https://github.com/glacambre/firenvim/issues/1549

update readme with more explicit language for url/page/element config

---

package-lock.json
package.json

Provide type annotation for browser

Add @types/firefox-webext-browser

---

src/FirenvimElement.ts

FirenvimElement.ts: use ctrlkey to trigger update events on textarea

---

package-lock.json
package.json

Necessary in order for the eslint ci to start working again

Upgrade to typescript 4.8.4

---

README.md

README.md: about:addons url fix

---

autoload/firenvim.vim

Add support for waterfox
